export const dogShows = [
  {
    id: 1,
    dogName: "Hugo",
    showName: "XXXVII Krajowa Wystawa Psów Rasowych",
    showPlace: "Gliwice",
    showDate: "10.04.2016",
    showJudge: "Monika Parasyn (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1 - Zwycięzca Młodzieży",
    showNameEng: "XXXVII National Dog Show",
    showDescriptionEng: "Youth class, excellent, 1st place - Youth Winner",
  },
  {
    id: 2,
    dogName: "Hugo",
    showName: "V Jesienna Krajowa Gorzowska Wystawa Psów Rasowych",
    showPlace: "Gorzów Wlkp.",
    showDate: "18.09.2016",
    showJudge: "Andrzej Stępiński (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1 - Zwycięzca Młodzieży i Najlepszy Junior w Rasie",
    showNameEng: "5th Autumn National Gorzów Dog Show",
    showDescriptionEng:
      "Youth class, excellent, 1st place - Youth Winner and Best Junior in Breed",
  },
  {
    id: 3,
    dogName: "Hugo",
    showName: "II Jesienna Wystawa Psów Rasowych",
    showPlace: "Jelenia Góra",
    showDate: "16.10.2016",
    showJudge: "Inga Siil (EST)",
    showDescription: "kl. Pośrednia, ocena doskonała, lokata 1 - CWC",
    showNameEng: "II Autumn Dog Show",
    showDescriptionEng: "Intermediate class, excellent, 1st place - CWC",
  },
  {
    id: 4,
    dogName: "Hugo",
    showName: "XLII Karkonoska Wystawa Psów Rasowych",
    showPlace: "Jelenia Góra",
    showDate: "30.04.2017",
    showJudge: "Aleksander Shishikin (BY)",
    showDescription:
      "kl. Pośrednia, ocena doskonała, lokata 1 - CWC, Najlepszy Dorosły Pies, Zwyciężca Rasy - BOB, BOG 4",
    showNameEng: "XLII Karkonosze Dog Show",
    showDescriptionEng:
      "Intermediate class, excellent, 1st place - CWC, Best Adult Dog, Best of Breed - BOB, BOG 4",
  },
  {
    id: 5,
    dogName: "Hugo",
    showName: "Krajowa Wystawa Psów Rasowych - PRESTIGE",
    showPlace: "Leszno",
    showDate: "04.06.2017",
    showJudge: "Grzegorz Weron (PL)",
    showDescription:
      "kl. Pośrednia, ocena doskonała, lokata 1 - CWC, Najlepszy Dorosły Pies, Zwycięzca Rasy - BOB, Zwyciężca Grupy 8, BIS 4",
    showNameEng: "National Dog Show - PRESTIGE",
    showDescriptionEng:
      "Intermediate class, excellent, 1st place - CWC, Best Adult Dog, Best of Breed - BOB, Best of Group 8, BIS 4",
  },
  {
    id: 6,
    dogName: "Nela",
    showName: "V Jesienna Krajowa Gorzowska Wystawa Psów Rasowych",
    showPlace: "Gorzów Wlkp.",
    showDate: "18.09.2016",
    showJudge: "Andrzej Stępiński (PL)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1/4 CC",
    showNameEng: "5th Autumn National Gorzów Dog Show",
    showDescriptionEng: "Open class, excellent, 1/4 CC",
  },
  {
    id: 7,
    dogName: "Nela",
    showName: "II Jesienna Wystawa Psów Rasowych",
    showPlace: "Jelenia Góra",
    showDate: "16.10.2016",
    showJudge: "Inga Siil (EST)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1/2 CWC",
    showNameEng: "II Autumn Dog Show",
    showDescriptionEng: "Open class, excellent, 1/2 place CWC",
  },
  {
    id: 8,
    dogName: "Nela",
    showName: "50. Jubileuszowa Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Gorzów Wlkp.",
    showDate: "15.07.2018",
    showJudge: "Fallon Clodagh (IRL)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1/4 CWC, res. CACIB",
    showNameEng: "50th Anniversary International Dog Show",
    showDescriptionEng: "Open class, excellent, 1/4 CWC, res. CACIB",
  },
  {
    id: 9,
    dogName: "Nela",
    showName: "X Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Legnickie Pole",
    showDate: "19.08.2018",
    showJudge: "Hanna Woźna-Gil (PL)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1/5 CWC",
    showNameEng: "10th National Hunting Dog Show",
    showDescriptionEng: "Open class, excellent, place 1/5 CWC",
  },
  {
    id: 10,
    dogName: "Aika",
    showName: "Krajowa Wystawa Psów Rasowych",
    showPlace: "Gdynia",
    showDate: "15-16.07.2017",
    showJudge: "Dusko Piljevic (RS), Vanessa Malkmus (DE)",
    showDescription: "kl. Szczeniąt, 2x ocena wybitnie obiecująca, 2x lokata 1",
    showNameEng: "National Dog Show",
    showDescriptionEng: "Puppy class, 2x very promising, 2x 1st place",
  },
  {
    id: 11,
    dogName: "Aika",
    showName: "XXII Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Katowice",
    showDate: "10.02.2018",
    showJudge: "Berchtold Peter (HU)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1/9 - Zwycięzca Młodzieży, Najlepszy Junior w Rasie, Nominacja na Cruft's 2019",
    showNameEng: "XXII International Dog Show",
    showDescriptionEng:
      "Youth class, excellent, place 1/9 - Youth Winner, Best Junior in Breed, Cruft's 2019 nomination",
  },
  {
    id: 12,
    dogName: "Aika",
    showName: "XXXIX Wiosenna Wystawa Psów Rasowych",
    showPlace: "Nowy Dwór Mazowiecki",
    showDate: "06.05.2018",
    showJudge: "Tomasz Mroczek (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1/3 - Zwycięzca Młodzieży, Najlepszy Junior w Rasie",
    showNameEng: "XXXIX Spring Dog Show",
    showDescriptionEng:
      "Youth class, excellent, 1/3 place - Youth Winner, Best Junior in Breed",
  },
  {
    id: 13,
    dogName: "Aika",
    showName: "3x CACIB SHOW - SZILVASVARAD HUNGARY",
    showPlace: "Szilvasvarad",
    showDate: "19-21.05.2018",
    showJudge: "Sean Delmar, Emma Archibald, Cristian Stefanescu",
    showDescription:
      "kl. Młodzieży, 3x ocena doskonała, 3x lokata 1 - 3x Zwycięzca Młodzieży = Młodzieżowy Champion Węgier",
    showNameEng: "3x CACIB SHOW - SZILVASVARAD HUNGARY",
    showDescriptionEng:
      "Youth class, 3x excellent, 3x 1st place - 3x Youth Winner = Youth Champion of Hungary",
  },
  {
    id: 14,
    dogName: "Aika",
    showName: "XLII Krajowa Wystawa Psów Rasowych",
    showPlace: "Kalisz",
    showDate: "10.06.2018",
    showJudge: "Maciej Lipiec (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1/6 - Zwycięzca Młodzieży, Najlepszy Junior w Rasie = Młodzieżowy Champion Polski",
    showNameEng: "XLII National Dog Show",
    showDescriptionEng:
      "Youth class, excellent, place 1/6 - Youth Winner, Best Junior in Breed = Polish Youth Champion",
  },
  {
    id: 15,
    dogName: "Aika",
    showName: "Krajowa Wystawa Psów Myśliwskich - Hubertus (duże CWC)",
    showPlace: "Spała / oddział Rybnik",
    showDate: "06.10.2018",
    showJudge: "Izabella Krasowska-Salamon (PL)",
    showDescription: "kl. Pośrednia, ocena doskonała, lokata 1/8 CWC",
    showNameEng: "National Hunting Dog Show - Hubertus (large CWC)",
    showDescriptionEng: "Intermediate class, excellent, 1/8 CWC",
  },
  {
    id: 16,
    dogName: "Aika",
    showName: "65. Krajowa Wystawa Psów Rasowych",
    showPlace: "Świebodzice / oddział Wałbrzych",
    showDate: "01-02.12.2018",
    showJudge: "Hanna Woźna-Gil (PL)",
    showDescription:
      "kl. Pośrednia, ocena doskonała, lokata 1/4 CWC - Najlepsza Dorosła Suka i Zwycięzca Płci Przeciwnej - BOS",
    showNameEng: "65th National Dog Show",
    showDescriptionEng:
      "Intermediate class, excellent, place 1/4 CWC - Best Adult female dog and Winner of the Opposite Sex - BOS",
  },
  {
    id: 17,
    dogName: "Aika",
    showName: "Krajowa Wystawa Psów Rasowych",
    showPlace: "Świebodzice / oddział Wałbrzych",
    showDate: "01.12.2019",
    showJudge: "Grzegorz Weron (PL)",
    showDescription:
      "kl. Otwarta, ocena doskonała, lokata 1/2 CWC - Najlepsza Dorosła Suka, Zwycięzca Rasy - BOB, BOG 4",
    showNameEng: "National Dog Show",
    showDescriptionEng:
      "Open class, excellent, place 1/2 CWC - Best Adult female dog, Best of Breed - BOB, BOG 4",
  },
  {
    ID: 18,
    dogName: "Aika",
    showName: "53. Toruńska Wystawa Psów Rasowych",
    showPlace: "Gołub-Dobrzyń",
    showDate: "15-16.08.2020",
    showJudge: "Leszek Sienkowski (PL)",
    showDescription: "kl. Championów, ocena doskonała, lokata 1 CWC",
    showNameEng: "53rd Toruń Dog Show",
    showDescriptionEng: "Champion class, excellent, 1st place CWC",
  },
  {
    id: 19,
    dogName: "Aika",
    showName: "CACIB UMAG - Chorwacja",
    showPlace: "Umag",
    showDate: "05-06.06.2021",
    showJudge: "Branislav Rajic",
    showDescription:
      "kl. Championów, ocena doskonała, lokata 1 CAC - rozpoczęty Championat Chorwacji",
    showNameEng: "CACIB UMAG - Croatia",
    showDescriptionEng:
      "Champion class, excellent, 1st place CAC - Croatian Championship started",
  },
  {
    id: 20,
    dogName: "Aika",
    showName: "Krajowa Wystawa Psów Rasowych",
    showPlace: "Łódź",
    showDate: "20.06.2021",
    showJudge: "Zofia Konderla (PL)",
    showDescription: "kl. Championów, ocena doskonała, lokata 1 CWC",
    showNameEng: "National Dog Show",
    showDescriptionEng: "Champion class, excellent, 1st place CWC",
  },
  {
    id: 21,
    dogName: "Kora",
    showName: "67. Krajowa Wystawa Psów Rasowych",
    showPlace: "Świebodzice / oddział Wałbrzych",
    showDate: "01.12.2019",
    showJudge: "Grzegorz Weron (PL)",
    showDescription:
      "kl. młodszych szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Młodsze Szczenię w Rasie",
    showNameEng: "National Dog Show",
    showDescriptionEng:
      "class of younger puppies, very promising, place 1 - Best Younger Puppy in Breed",
  },
  {
    id: 22,
    dogName: "Kora",
    showName: "III Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Wrocław",
    showDate: "29.08.2021",
    showJudge: "Anna Pulikowska-Klimonda (PL)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1/2 CWC",
    showNameEng: "III National Hunting Dog Show",
    showDescriptionEng: "Open class, excellent, 1/2 place CWC",
  },
  {
    id: 23,
    dogName: "Kora",
    showName: "Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Kliczków / oddział Legnica",
    showDate: "07.05.2022",
    showJudge: "Hanna Woźna-Gil (PL)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1 CWC",
    showNameEng: "International Dog Show",
    showDescriptionEng: "Open class, excellent, 1st place, CWC",
  },
  {
    id: 24,
    dogName: "Kora",
    showName: "XXIV Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Kraków",
    showDate: "11-12.06.2022",
    showJudge: "Fallon Clodagh (IE)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1/10 CWC",
    showNameEng: "XXIV International Dog Show",
    showDescriptionEng: "Open class, excellent, place 1/10 CWC",
  },
  {
    id: 25,
    dogName: "Kora",
    showName: "XII Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Legnickie Pole",
    showDate: "20.08.2022",
    showJudge: "Piotr Król (PL)",
    showDescription:
      "kl. Championów, ocena doskonała, lokata 1 CWC - Najlepsza Dorosła Suka",
    showNameEng: "XII National Hunting Dog Show",
    showDescriptionEng:
      "Champion class, excellent, 1st place CWC - Best Adult Female",
  },
  {
    id: 26,
    dogName: "Ana",
    showName: "CACIB UMAG - Chorwacja",
    showPlace: "Umag",
    showDate: "05-06.06.2021",
    showJudge: "Darko Martinovic (HR), Branislav Rajic (SI)",
    showDescription:
      "kl. Szczeniąt, 2x ocena wybitnie obiecująca, 2x lokata 1 - 2x Najlepsze Szczenię w Rasie",
    showNameEng: "CACIB UMAG - Croatia",
    showDescriptionEng:
      "Puppy class, 2x very promising, 2x 1st place - 2x Best Puppy in Breed",
  },
  {
    id: 27,
    dogName: "Ana",
    showName: "XLVII Karkonoska Wystawa Psów Rasowych",
    showPlace: "Jelenia Góra",
    showDate: "17.07.2021",
    showJudge: "Hanna Woźna-Gil (PL)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Szczenię w Rasie",
    showNameEng: "XLVII Karkonosze Dog Show",
    showDescriptionEng:
      "Puppy class, very promising, 1st place - Best Puppy in Breed",
  },
  {
    id: 28,
    dogName: "Ana",
    showName: "6. Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Częstochowa",
    showDate: "24-25.07.2021",
    showJudge: "Judit Bede (HU)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Szczenię w Rasie",
    showNameEng: "6th International Dog Show",
    showDescriptionEng:
      "Puppy class, very promising, 1st place - Best Puppy in Breed",
  },
  {
    id: 29,
    dogName: "Ana",
    showName: "XI Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Łącko / oddział Bydgoszcz",
    showDate: "03.10.2021",
    showJudge: "Małgorzata Lorenc (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1/2 - Zwycięzca Młodzieży",
    showNameEng: "11th National Hunting Dog Show",
    showDescriptionEng: "Youth class, excellent, 1st/2nd place - Youth Winner",
  },
  {
    id: 30,
    dogName: "Ana",
    showName: "48. Krajowa Wystawa Psów Rasowych",
    showPlace: "Zabrze",
    showDate: "10.10.2021",
    showJudge: "Wojciech Burski (PL)",
    showDescription:
      "kl. Młodziezy, ocena doskonała, lokata 1/3 - Zwycięzca Młodzieży",
    showNameEng: "48th National Dog Show",
    showDescriptionEng: "Youth class, excellent, 1st place/3 - Youth Winner",
  },
  {
    id: 31,
    dogName: "Ana",
    showName: "XXIV Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Kraków",
    showDate: "11-12.06.2022",
    showJudge: "Fallon Clodagh (Ie)",
    showDescription: "kl. Młodzieży, ocena doskonała, lokata 3/13",
    showNameEng: "XXIV International Dog Show",
    showDescriptionEng: "Youth class, excellent, 3rd place/13",
  },
  {
    id: 32,
    dogName: "Ana",
    showName: "XXVI Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Szczecin",
    showDate: "18-19.06.2022",
    showJudge: "Tomasz Mroczek (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1/2 - Zwycięzca Młodzieży",
    showNameEng: "XXVI International Dog Show",
    showDescriptionEng: "Youth class, excellent, 1st/2nd place - Youth Winner",
  },
  {
    id: 33,
    dogName: "Ana",
    showName: "XLIX Karkonoska Wystawa Psów Rasowych",
    showPlace: "Jelenia Góra",
    showDate: "26.06.2022",
    showJudge: "Dragon Babic (RS)",
    showDescription:
      "kl. Pośrednia, ocena doskonała, lokata 1/2 CWC - Najlepsza Dorosła Suka i Zwycięzca Płci Przeciwnej - BOS",
    showNameEng: "XLIX Karkonosze Dog Show",
    showDescriptionEng:
      "Intermediate class, excellent, 1/2 CWC - Best Adult Bitch and Winner of the Opposite Sex - BOS",
  },
  {
    id: 34,
    dogName: "Ana",
    showName: "IV Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Bydgoszcz",
    showDate: "09-10.07.2022",
    showJudge: "Izabella Krasowska-Salamon (PL)",
    showDescription: "kl. Pośrednia, ocena doskonała, lokata 1/3 CWC",
    showNameEng: "IV International Dog Show",
    showDescriptionEng: "Intermediate class, excellent, 1/3 CWC",
  },
  {
    id: 35,
    dogName: "Ana",
    showName: "Klubowa Wystawa Retrieverów",
    showPlace: "Częstochowa",
    showDate: "23.07.2022",
    showJudge: "Margaret Brown (GB)",
    showDescription: "kl. Pośrednia, ocena doskonała, lokata 2/12",
    showNameEng: "Retriever Club Show",
    showDescriptionEng: "Intermediate class, excellent, place 2/12",
  },
  {
    id: 36,
    dogName: "Ana",
    showName: "XII Krajowa Wystawa Psów Mysliwskich",
    showPlace: "Legnickie Pole",
    showDate: "20.08.2022",
    showJudge: "Piotr Król (PL)",
    showDescription: "kl. Pośrednia, ocena doskonała, lokata 1 CWC",
    showNameEng: "XII National Hunting Dog Show",
    showDescriptionEng: "Intermediate class, excellent, 1st place, CWC",
  },
  {
    id: 37,
    dogName: "Ana",
    showName: "XXVI Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Katowice",
    showDate: "11-12.02.2023",
    showJudge: "Hanna Woźna-Gil (PL)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1/4 CWC",
    showNameEng: "XXVI International Dog Show",
    showDescriptionEng: "Open class, excellent, 1/4 CWC, res. CACIB",
  },
  {
    id: 38,
    dogName: "Frida",
    showName: "Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Poznań",
    showDate: "05-06.11.2022",
    showJudge: "Fabrizio La Rocca (IT), Maria-Luise Doppelreiter (AT)",
    showDescription:
      "kl. Młodszych Szczeniąt, ocena wybitnie obiecująca, 2x lokata 1, 2x Najlepsze Młodsze Szczenię w Rasie",
    showNameEng: "International Dog Show",
    showDescriptionEng:
      "Minor Puppy Class, very promising, 2x 1st place, 2x Best Minor Puppy in Breed",
  },
  {
    id: 39,
    dogName: "Frida",
    showName: "VIII Krajowa Wystawa Psów Rasowych",
    showPlace: "Brodnica / oddział Toruń",
    showDate: "14-15.01.2023",
    showJudge: "Lenka Frncova (CZ)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Szczenię w Rasie",
    showNameEng: "VIII National Dog Show",
    showDescriptionEng:
      "Puppy class, very promising, 1st place - Best Puppy in Breed",
  },
  {
    id: 40,
    dogName: "Frida",
    showName: "IX Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Lubin",
    showDate: "21-22.01.2023",
    showJudge: "Bogusława Szydłowicz-Polańczyk (PL)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1/2 - Najlepsze Szczenię w Rasie",
    showNameEng: "IX International Dog Show",
    showDescriptionEng:
      "Puppy class, very promising, 1/2 place - Best Puppy in Breed",
  },
  {
    id: 41,
    dogName: "Frida",
    showName: "XXVI Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Katowice",
    showDate: "11-12.02.2023",
    showJudge: "Hanna Woźna-Gil (PL)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1/2 - Najlepsze Szczenię w Rasie",
    showNameEng: "XXVI International Dog Show",
    showDescriptionEng:
      "Puppy class, very promising, 1/2 place - Best Puppy in Breed",
  },
  {
    id: 42,
    dogName: "Frida",
    showName: "Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Przechlewo / oddział Chojnice",
    showDate: "23.04.2023",
    showJudge: "Katarzyna Szutkiewicz (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1/2 - Zwycięzca Młodzieży, Najlepszy Junior, Zwycięzca Rasy - BOB, Zwycięzca Grupy 8 - BOG",
    showNameEng: "National Hunting Dog Show - Hubertus (large CWC)",
    showDescriptionEng:
      "Youth class, excellent, 1/2 place - Youth Winner, Best Junior, Best of Breed - BOB, Winner of Group 8 - BOG",
  },
  {
    id: 43,
    dogName: "Frida",
    showName: "XIII Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Kliczków / oddział Legnica",
    showDate: "26.08.2023",
    showJudge: "Tomasz Kliś (PL)",
    showDescription: "kl. Młodzieży, ocena doskonała, lokata 1",
    showNameEng: "XIII National Hunting Dog Show",
    showDescriptionEng: "Youth class, excellent, 1st place",
  },
  {
    id: 44,
    dogName: "Frida",
    showName: "DANUBE CACIB",
    showPlace: "Bratysława",
    showDate: "28.10.2023",
    showJudge: "Oliveira Rui (PT)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1 - CACJ, FCI-CACIB-J, BOJ",
    showNameEng: "DANUBE CACIB",
    showDescriptionEng:
      "Youth class, excellent, 1st place - CACJ, FCI-CACIB-J, BOJ",
  },
  {
    id: 45,
    dogName: "Frida",
    showName: "DANUBE CACIB",
    showPlace: "Bratysława",
    showDate: "29.10.2023",
    showJudge: "Katarzyna Szutkiewicz (PL)",
    showDescription: "kl. Młodzieży, ocena doskonała, lokata 2/4",
    showNameEng: "DANUBE CACIB",
    showDescriptionEng: "Youth class, excellent, 2/4 place",
  },
  {
    id: 46,
    dogName: "Frida",
    showName: "Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Poznań",
    showDate: "05.11.2023",
    showJudge: "Alessandro Zeppi (IT)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1/4 - Zwycięzca Młodzieży, Najlepszy Junior - CACIB - Junior",
    showNameEng: "International Dog Show",
    showDescriptionEng:
      "Youth class, excellent, place 1/4 - Youth Winner, Best Junior - CACIB - Junior",
  },
  {
    id: 47,
    dogName: "Frida",
    showName: "CACIB Nitra",
    showPlace: "Nitra",
    showDate: "18.02.2024",
    showJudge: "Alessandro Zeppi (IT)",
    showDescription: "kl. Pośrednia, ocena doskonała, lokata 2/6 res. CAC",
    showNameEng: "CACIB Nitra",
    showDescriptionEng: "Intermediate class, excellent, place 2/6 res. CAC",
  },
  {
    id: 48,
    dogName: "Frida",
    showName: "72. Krajowa Wystawa Psów Rasowych",
    showPlace: "Świebodzice / oddział Wałbrzych",
    showDate: "06-07.04.2024",
    showJudge: "Jakub Rudziński (PL)",
    showDescription: "kl. Posrednia, ocena doskonała, lokata 1 CWC",
    showNameEng: "72nd National Dog Show",
    showDescriptionEng: "Intermediate class, excellent, 1st place, CWC",
  },
  {
    id: 49,
    dogName: "Frida",
    showName: "Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Przechlewo / oddział Chojnice",
    showDate: "21.04.2024",
    showJudge: "Ewa Kotowska (PL)",
    showDescription:
      "kl. Pośrednia, ocena doskonała, lokata 1/2 CWC - Najlepsza Dorosła Suka, Zwycięzca Rasy - BOB, BOG4",
    showNameEng: "National Hunting Dog Show",
    showDescriptionEng:
      "Intermediate class, excellent, 1/2 CWC - Best Adult female dog, Best of Breed - BOB, BOG4",
  },
  {
    id: 50,
    dogName: "Frida",
    showName: "V Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Koszalin - Czaplinek",
    showDate: "07.09.2024",
    showJudge: "Etemi Vigan (XK)",
    showDescription: "kl. Otwarta, ocena doskonała, lokata 1 CWC",
    showNameEng: "5th International Dog Show",
    showDescriptionEng: "Open class, excellent, 1st place, CWC",
  },
  {
    id: 51,
    dogName: "Teddy",
    showName: "Klubowa Wystawa Retrieverów",
    showPlace: "Kobiór / oddział Bielsko-Biała",
    showDate: "01.05.2023",
    showJudge: "Pia Itkonen (FI)",
    showDescription:
      "kl. Młodszych Szczeniąt, ocena wybitnie obiecująca, lokata 2",
    showNameEng: "Retriever Club Show",
    showDescriptionEng: "Minor Puppy class, very promising, 2nd place",
  },
  {
    id: 52,
    dogName: "Teddy",
    showName: "Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Kobiór / oddział Bielsko-Biała",
    showDate: "01.05.2023",
    showJudge: "Marek Tobiasz (PL)",
    showDescription:
      "kl. Młodszych Szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Szczenię w Rasie",
    showNameEng: "National Hunting Dog Show",
    showDescriptionEng:
      "Minor Puppy, very promising, place 1 - Best Puppy in Breed",
  },
  {
    id: 53,
    dogName: "Teddy",
    showName: "XII Krajowa Wystawa Psów Mysliwskich",
    showPlace: "Kliczków / oddział Legnica",
    showDate: "26.08.2023",
    showJudge: "Tomasz Kliś (PL)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Szczenię w Rasie",
    showNameEng: "XII National Hunting Dog Show",
    showDescriptionEng:
      "Puppy class, very promising, 1st place - Best Puppy in Breed",
  },
  {
    id: 54,
    dogName: "Teddy",
    showName: "DANUBE CACIB",
    showPlace: "Bratysława",
    showDate: "28.10.2023",
    showJudge: "Oliveira Rui (PT)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1, CAJC, FCI-CACIB-J",
    showNameEng: "DANUBE CACIB",
    showDescriptionEng: "Youth class, excellent, 1st place, CAJC, FCI-CACIB-J",
  },
  {
    id: 55,
    dogName: "Teddy",
    showName: "VI Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Bydgoszcz",
    showDate: "17-18.02.2024",
    showJudge: "Izabella Krasowska-Salamon (PL)",
    showDescription: "kl. Młodzieży, ocena doskonała, lokata 2",
    showNameEng: "VI International Dog Show",
    showDescriptionEng: "Youth class, excellent, 2nd place",
  },
  {
    id: 56,
    dogName: "Teddy",
    showName: "72. Krajowa Wystawa Psów Rasowych",
    showPlace: "Świebodzice / oddział Wałbrzych",
    showDate: "06-07.04.2024",
    showJudge: "Jakub Rudziński (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1/2 - Zwycięzca Młodzieży i Najlepszy Junior w Rasie",
    showNameEng: "72nd National Dog Show",
    showDescriptionEng:
      "Youth class, excellent, 1/2 place - Youth Winner and Best Junior in Breed",
  },
  {
    id: 57,
    dogName: "Teddy",
    showName: "Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Przechlewo / oddział Chojnice",
    showDate: "21.04.2024",
    showJudge: "Ewa Kotowska (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1 - Zwycięzca Młodzieży i Najlepszy Junior w Rasie",
    showNameEng: "National Hunting Dog Show",
    showDescriptionEng:
      "Youth class, excellent, 1st place - Youth Winner and Best Junior in Breed",
  },
  {
    id: 58,
    dogName: "Teddy",
    showName: "Krajowa Wystawa Psów 1, 6, 7 i 8 grupy FCI",
    showPlace: "Babimot / oddział Zielona Góra",
    showDate: "18.05.2024",
    showJudge: "Tomasz Kliś (PL)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1 - Zwycięzca Młodzieży i Najlepszy Junior w Rasie",
    showNameEng: "National Dog Show 1, 6, 7 and 8 FCI group",
    showDescriptionEng:
      "Youth class, excellent, 1st place - Youth Winner and Best Junior in Breed",
  },
  {
    id: 59,
    dogName: "Teddy",
    showName: "XVII Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Bytom",
    showDate: "08.06.2024",
    showJudge: "Kimmo Mustonen (FI)",
    showDescription:
      "kl. Młodzieży, ocena doskonała, lokata 1 - Zwycięzca Młodzieży i Najlepszy Junior w Rasie - CACIB-Junior",
    showNameEng: "XVII International Dog Show",
    showDescriptionEng:
      "Youth class, excellent, 1st place - Youth Winner and Best Junior in Breed - CACIB-Junior",
  },
  {
    id: 60,
    dogName: "Teddy",
    showName: "Krajowa Wystawa Psów Mysliwskich",
    showPlace: "Częstochowa",
    showDate: "19.07.2024",
    showJudge: "Tomasz Kliś (PL)",
    showDescription:
      "kl. Posrednia, ocena doskonała, lokata 1 - CWC, Najlepszy Dorosły Pies, Zwycięzca asy - BOB",
    showNameEng: "National Hunting Dog Show",
    showDescriptionEng:
      "Intermediate class, excellent, 1st place - CWC, Best Adult Dog, Winner of the Ace - BOB",
  },
  {
    id: 61,
    dogName: "Teddy",
    showName: "10. Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Częstochowa",
    showDate: "20.07.2024",
    showJudge: "Agnieszka Skórzewska (PL)",
    showDescription:
      "kl. Pośrednia, ocena doskonała, lokata 1 - CWC, res. CACIB",
    showNameEng: "10th International Dog Show",
    showDescriptionEng:
      "Intermediate class, excellent, 1st place - CWC, res. CACIB",
  },
  {
    id: 62,
    dogName: "River",
    showName: "XIV Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Legnica",
    showDate: "15.08.2024",
    showJudge: "Joanna Sołtys (PL)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Szczenię i Najlepsze Szczenię w Rasie",
    showNameEng: "14th National Hunting Dog Show",
    showDescriptionEng:
      "Puppy class, very promising, 1st place - Best Puppy and Best Puppy in Breed",
  },
  {
    id: 63,
    dogName: "River",
    showName: "V Międzynarodowa Wystawa Psów Rasowych",
    showPlace: "Koszalin - Czaplinek",
    showDate: "07-08.09.2024",
    showJudge: "Vigan Etemi (XK)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Szczenię i Najlepsze Szczenię w Rasie",
    showNameEng: "5th International Dog Show",
    showDescriptionEng:
      "Puppy class, very promising, 1st place - Best Puppy and Best Puppy in Breed",
  },
  {
    id: 64,
    dogName: "River",
    showName: "XVIII Krajowa Wystawa Psów Myśliwskich",
    showPlace: "Czaplinek / Oddział Koszalin",
    showDate: "07.09.2024",
    showJudge: "Marek Tobiasz (PL)",
    showDescription:
      "kl. Szczeniąt, ocena wybitnie obiecująca, lokata 1 - Najlepsze Szczenię",
    showNameEng: "XVIII National Hunting Dog Show",
    showDescriptionEng: "Puppy class, very promising, 1st place - Best Puppy",
  },
  {
    id: 65,
    dogName: "Frida",
    showName: "55. Jesienna Wystawa Psów Rasowych",
    showPlace: "Nowy Dwór Mazowiecki/Oddział Legionowo",
    showDate: "13.10.2024",
    showJudge: "Joanna Dąbrowska (PL)",
    showDescription:
      "kl. Otwarta, ocena doskonała, lokata 1/2 CWC - Najlepsza Dorosła Suka oraz Zwycięzca Płci Przeciwnej BOS",
    showNameEng: "55th Autumn Dog Show",
    showDescriptionEng:
      "Open class, excellent, 1/2 CWC - Best Adult Bitch and Winner of the Opposite Sex BOS",
  },
];
